--ALTER TABLE MBANKBNCDV.ACCREDITED_BILLER_USER DROP COLUMN USERNAME;
ALTER TABLE MBANKBNCDV.ACCREDITED_BILLER_USER ADD USERNAME VARCHAR(25) DEFAULT NULL;
ALTER TABLE MBANKBNCDV.ACCREDITED_BILLER_USER ADD OTP_REQUESTED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE MBANKBNCDV.ACCREDITED_BILLER_USER ADD LOGIN_ATTEMPTS INTEGER DEFAULT NULL;
ALTER TABLE MBANKBNCDV.ACCREDITED_BILLER_USER ADD OTP_ATTEMPTS INTEGER DEFAULT NULL;
ALTER TABLE MBANKBNCDV.ACCREDITED_BILLER_USER ADD OTP VARCHAR(25) DEFAULT NULL;

